name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  mariadb:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          project: r2dbc-mariadb

  mysql:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          project: r2dbc-mysql

  postgresql:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          project: r2dbc-postgres